name: lcwm
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - seaborn
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  # pip==21.3.1 setuptools==59.5.0 でないと pydreamer の依存パッケージである、gym 0.19.0 がインストールできない
  - pip:
      - captum
      - xplique
      - opencv-python
